# Database connection, MariaDB and MYSQL supported, no sqllite
Database: "jdbc:mariadb://0.0.0.0:3306/Database"
Username: ""
Password: ""

Commands:
  Team:
    permission: "gamingteams.commands.team"
    # aliases will unregister other commands using this name
    aliases:
      - team
    SubCommands:
      add: "add"
      remove: "remove"
      name: "name"
      tag: "tag"
      member: "member"
      leave: "leave"
    Arguments:
      name: "name"
      tag: "tag"
      owner: "owner"
      player: "player"

Messages:
  alreadyInTeam: "<red>Your are already in a team</red>"
  notOwner: "<red>You are not the owner of your team.</red>"
  removedTeam: "<green>Your team was succesfully removed.</green>"
  teamNameInUse: "<red>This team name is already in use</red>"
  notInATeam: "<red>You are not in a team!</red>"
  leaftTeam: "You leaft your team."
  cannotRemovePlayer: "<red>You cannot remove that player from your team!</red>"
  ownerCannotLeave: "<red>The owner of a team cannot leave it, remove the team or give an other Person the owner privilige.</red>"
  removeSelf: "<red>You cannot remove you self from a team!</red>"
  inviteSelf: "<red>You cannot invitze your self to a team!</red>"
  # Placeholder: <name>
  addTeam: "<green>You succesfully added yout Team <name>.</green>"
  changeName: "<green>You succesfully changes the teams name to <name>.</green>"
  invited: "You got invited in the team <name>."
  # Placeholder: <tag>
  changeTag: "<green>You succesfully changes the teams tag to <tag>.</green>"
  # Placeholder: <player>
  invitedPlayer: "<green>You invited <player>.</green>"
