# Database connection, MariaDB and MYSQL supported, no sqllite
Database: "jdbc:mariadb://0.0.0.0:3306/Database"
Username: ""
Password: ""

Commands:
  Team:
    permission: "gamingteams.commands.team"
    # aliases will unregister other commands using this name
    aliases:
      - team
    SubCommands:
      add: "add"
      remove: "remove"
      name: "name"
      tag: "tag"
      member: "member"
      leave: "leave"
    Arguments:
      name: "name"
      tag: "tag"
      owner: "owner"
      player: "player"

Messages:
  alreadyInTeam: "<red>Your are already in a team</red>"
  notOwner: "<red>You are not the owner of this your team.</red>"
  removedTeam: "<green>Your team was succesfully removed.</green>"
  # Placeholder: <name>
  addTeam: "<green>You succesfully added yout Team <name>.</green>"
