# Database connection, MariaDB and MYSQL supported, no sqllite
Database: "jdbc:mariadb://0.0.0.0:3306/Database"
Username: ""
Password: ""

Commands:
  Team:
    permission: "gamingteams.commands.team"
    # aliases will unregister other commands using this name
    aliases:
      - team
    SubCommands:
      add: "add"
      remove: "remove"
      name: "name"
      tag: "tag"
      member: "member"
      leave: "leave"
      join: "join"
      owner: "owner"
    Arguments:
      name: "name"
      tag: "tag"
      owner: "owner"
      player: "player"
      teams: "teams"
      info: "info"
      list: "list"
