name: Gamingteams
version: "${version}"
main: me.gaminglounge.gamingteams.Gamingteams
loader: me.gaminglounge.gamingteams.GamingteamsLoader
description:
api-version: "1.21.4"
authors:
  - "Jon1Games"
