name: Gamingteams
version: "${version}"
main: me.gaminglounge.gamingteams.Gamingteams
loader: me.gaminglounge.gamingteams.GamingteamsLoader
description:
api-version: "1.21.4"
authors:
  - "Jon1Games"
dependencies:
  server:
    ConfigAPI:
      load: BEFORE
      required: true
      join-classpath: true
    GuiAPI:
      load: BEFORE
      required: true
      join-classpath: true
    ItemBuilder:
      load: BEFORE
      required: true
      join-classpath: true
    WorldGuard:
      load: BEFORE
      required: false
      join-classpath: true
    PlayerInputAPI:
      load: BEFORE
      required: false
      join-classpath: true
    PlaceholderAPI:
      load: BEFORE
      required: true
